# Generated by Django 5.2.5 on 2025-09-17 17:38

import django.core.validators
import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CostCenter',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('nome', models.CharField(max_length=150, unique=True, verbose_name='Nome do Centro de Custo')),
                ('codigo', models.CharField(max_length=30, unique=True, verbose_name='Código interno')),
                ('cliente', models.CharField(blank=True, max_length=150, verbose_name='Cliente (Razão/Nome Fantasia)')),
                ('ativo', models.BooleanField(default=True, verbose_name='Ativo')),
                ('contato_nome', models.CharField(blank=True, max_length=100, verbose_name='Contato principal')),
                ('contato_email', models.EmailField(blank=True, max_length=254, verbose_name='E-mail do contato')),
                ('contato_telefone', models.CharField(blank=True, max_length=30, verbose_name='Telefone do contato')),
                ('contrato_inicio', models.DateField(blank=True, null=True, verbose_name='Início do contrato')),
                ('contrato_fim', models.DateField(blank=True, null=True, verbose_name='Fim do contrato')),
                ('orcamento_total', models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Orçamento total (R$)')),
                ('horas_previstas', models.DecimalField(blank=True, decimal_places=2, max_digits=9, null=True, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Horas-homem previstas')),
                ('criado_em', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('atualizado_em', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
            ],
            options={
                'verbose_name': 'Centro de Custo',
                'verbose_name_plural': 'Centros de Custo',
                'ordering': ['nome'],
            },
        ),
        migrations.CreateModel(
            name='AllowedDomain',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('dominio', models.CharField(max_length=255, validators=[django.core.validators.RegexValidator(message='Informe um domínio válido, ex.: empresa.com.br', regex='^[a-z0-9.-]+\\.[a-z]{2,}$')], verbose_name='Domínio de e-mail')),
                ('ativo', models.BooleanField(default=True, verbose_name='Ativo')),
                ('criado_em', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('centro', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dominios_permitidos', to='projetos.costcenter')),
            ],
            options={
                'verbose_name': 'Domínio permitido',
                'verbose_name_plural': 'Domínios permitidos',
                'indexes': [models.Index(fields=['centro', 'ativo'], name='projetos_al_centro__09dd45_idx')],
                'unique_together': {('centro', 'dominio')},
            },
        ),
    ]
