# Generated by Django 5.2.5 on 2025-09-17 18:44

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projetos', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CostCenterMember',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('papel', models.CharField(choices=[('GESTOR', 'Gestor'), ('COLAB', 'Colaborador')], default='COLAB', max_length=10, verbose_name='Papel')),
                ('ativo', models.BooleanField(default=True, verbose_name='Ativo')),
                ('criado_em', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('centro', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='membros', to='projetos.costcenter')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='centros_membro', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Membro do Centro',
                'verbose_name_plural': 'Membros do Centro',
                'indexes': [models.Index(fields=['centro', 'papel'], name='projetos_co_centro__4a9cce_idx')],
                'unique_together': {('centro', 'usuario')},
            },
        ),
    ]
