# Generated by Django 5.2.5 on 2025-09-17 20:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projetos', '0002_costcentermember'),
    ]

    operations = [
        migrations.AddField(
            model_name='costcenter',
            name='background_image',
            field=models.ImageField(blank=True, null=True, upload_to='centros_bg/', verbose_name='Imagem de fundo do card'),
        ),
    ]
