# Generated by Django 5.2.5 on 2025-09-18 12:44

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projetos', '0003_costcenter_background_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('centro', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='projetos', to='projetos.costcenter')),
            ],
        ),
    ]
