# Generated by Django 5.2.5 on 2025-09-18 13:09

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projetos', '0004_project'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='project',
            options={'ordering': ['nome'], 'verbose_name': 'Projeto', 'verbose_name_plural': 'Projetos'},
        ),
        migrations.AddField(
            model_name='project',
            name='ativo',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='project',
            name='nome',
            field=models.CharField(default=1, max_length=120, verbose_name='Nome do projeto'),
            preserve_default=False,
        ),
        migrations.AlterUniqueTogether(
            name='project',
            unique_together={('centro', 'nome')},
        ),
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('nome', models.CharField(max_length=200, verbose_name='Nome da tarefa')),
                ('orientacoes', models.TextField(blank=True, verbose_name='Orientações')),
                ('data_inicio_prevista', models.DateField(blank=True, null=True)),
                ('data_fim_prevista', models.DateField(blank=True, null=True)),
                ('horas_homem_previstas', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
                ('recorrencia_dias', models.PositiveSmallIntegerField(default=0, help_text='Seg=1, Ter=2, Qua=4, Qui=8, Sex=16, Sáb=32, Dom=64 (some para combinar).', verbose_name='Dias da semana (máscara)')),
                ('hora_publicacao', models.TimeField(blank=True, null=True, verbose_name='Horário para aparecer')),
                ('encerra_no_fim_do_dia', models.BooleanField(default=True, verbose_name='Encerrar às 23:59 do mesmo dia')),
                ('status', models.CharField(choices=[('OPEN', 'Aberta'), ('DOING', 'Em andamento'), ('PAUSE', 'Pausada'), ('REVIEW', 'Em avaliação'), ('DONE', 'Concluída')], default='OPEN', max_length=10, verbose_name='Status')),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('autorizados', models.ManyToManyField(blank=True, help_text='Usuários que podem registrar atividades nesta tarefa.', related_name='tarefas_autorizadas', to=settings.AUTH_USER_MODEL)),
                ('centro', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tarefas', to='projetos.costcenter')),
                ('criado_por', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='tarefas_criadas', to=settings.AUTH_USER_MODEL)),
                ('projeto', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='tarefas', to='projetos.project')),
            ],
            options={
                'verbose_name': 'Tarefa',
                'verbose_name_plural': 'Tarefas',
                'ordering': ['-criado_em'],
                'indexes': [models.Index(fields=['centro', 'projeto', 'status'], name='projetos_ta_centro__35f98c_idx')],
            },
        ),
    ]
