# Generated by Django 5.2.5 on 2025-08-14 17:15

import django.db.models.deletion
import django.utils.timezone
import solicitacoes.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TipoSolicitacao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=120, unique=True)),
                ('descricao', models.TextField(blank=True)),
                ('ativo', models.BooleanField(default=True)),
                ('criado_em', models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                'ordering': ['nome'],
            },
        ),
        migrations.CreateModel(
            name='Chamado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('aberto', 'Aberto'), ('em_andamento', 'Em andamento'), ('concluido', 'Concluído')], default='aberto', max_length=20)),
                ('tratativa_adm', models.TextField(blank=True)),
                ('criado_em', models.DateTimeField(default=django.utils.timezone.now)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('solicitante', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chamados', to=settings.AUTH_USER_MODEL)),
                ('tipo', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='chamados', to='solicitacoes.tiposolicitacao')),
            ],
            options={
                'ordering': ['-criado_em'],
            },
        ),
        migrations.CreateModel(
            name='PerguntaTipoSolicitacao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('texto', models.CharField(max_length=255)),
                ('tipo_campo', models.CharField(choices=[('text', 'Texto curto'), ('textarea', 'Texto longo'), ('int', 'Número inteiro'), ('decimal', 'Número decimal'), ('date', 'Data'), ('datetime', 'Data e hora'), ('bool', 'Sim/Não'), ('choice', 'Escolha única'), ('multichoice', 'Múltipla escolha'), ('file', 'Arquivo')], default='text', max_length=20)),
                ('obrigatoria', models.BooleanField(default=True)),
                ('ajuda', models.CharField(blank=True, max_length=255)),
                ('ordem', models.PositiveIntegerField(default=1)),
                ('opcoes', models.CharField(blank=True, help_text='Para escolha/múltipla escolha, separe as opções por ponto e vírgula (;)', max_length=800)),
                ('ativa', models.BooleanField(default=True)),
                ('tipo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='perguntas', to='solicitacoes.tiposolicitacao')),
            ],
            options={
                'ordering': ['ordem', 'id'],
            },
        ),
        migrations.CreateModel(
            name='RespostaChamado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('valor_texto', models.TextField(blank=True)),
                ('valor_arquivo', models.FileField(blank=True, null=True, upload_to=solicitacoes.models.anexo_upload_path)),
                ('chamado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='respostas', to='solicitacoes.chamado')),
                ('pergunta', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='respostas', to='solicitacoes.perguntatiposolicitacao')),
            ],
            options={
                'ordering': ['pergunta__ordem', 'pergunta_id'],
                'unique_together': {('chamado', 'pergunta')},
            },
        ),
    ]
