# Generated by Django 5.2.5 on 2025-08-14 18:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('solicitacoes', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='tiposolicitacao',
            name='setores_permitidos',
            field=models.CharField(blank=True, help_text="Digite os nomes dos setores autorizados separados por ';'. Ex.: RH; Financeiro; TI. Vazio = todos.", max_length=300),
        ),
    ]
