# Generated by Django 5.2.5 on 2025-08-15 11:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('solicitacoes', '0002_tiposolicitacao_setores_permitidos'),
    ]

    operations = [
        migrations.AddField(
            model_name='chamado',
            name='suspenso_em',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='chamado',
            name='status',
            field=models.CharField(choices=[('aberto', 'Aberto'), ('em_andamento', 'Em andamento'), ('concluido', 'Concluído'), ('suspenso', 'Suspenso'), ('cancelado', 'Cancelado')], default='aberto', max_length=20),
        ),
    ]
