# Generated by Django 5.2.5 on 2025-08-15 12:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('solicitacoes', '0003_chamado_suspenso_em_alter_chamado_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='chamado',
            name='atendente_nome',
            field=models.CharField(blank=True, max_length=120),
        ),
    ]
