# Generated by Django 5.2.5 on 2025-08-15 12:39

import solicitacoes.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('solicitacoes', '0004_chamado_atendente_nome'),
    ]

    operations = [
        migrations.AddField(
            model_name='chamado',
            name='anexo_adm',
            field=models.FileField(blank=True, null=True, upload_to=solicitacoes.models.anexo_adm_upload_path),
        ),
    ]
