# Generated by Django 5.2.5 on 2025-08-22 18:53

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('solicitacoes', '0006_secaovista'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ChamadoMensagem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('texto', models.TextField()),
                ('anexo', models.FileField(blank=True, null=True, upload_to='chamados/mensagens/')),
                ('visibilidade', models.CharField(choices=[('publica', 'Pública'), ('interna', 'Interna')], default='publica', max_length=10)),
                ('tipo_evento', models.CharField(blank=True, default='mensagem', max_length=30)),
                ('meta', models.JSONField(blank=True, null=True)),
                ('criado_em', models.DateTimeField(default=django.utils.timezone.now)),
                ('autor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('chamado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mensagens', to='solicitacoes.chamado')),
            ],
            options={
                'ordering': ['criado_em'],
            },
        ),
    ]
