# Generated by Django 5.2.5 on 2025-08-25 18:28

import django.db.models.deletion
import django.utils.timezone
import solicitacoes.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('solicitacoes', '0007_chamadomensagem'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ChamadoVista',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_seen', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.AlterUniqueTogether(
            name='respostachamado',
            unique_together=set(),
        ),
        migrations.AlterUniqueTogether(
            name='secaovista',
            unique_together=set(),
        ),
        migrations.AlterField(
            model_name='chamado',
            name='criado_em',
            field=models.DateTimeField(db_index=True, default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='chamado',
            name='status',
            field=models.CharField(choices=[('aberto', 'Aberto'), ('em_andamento', 'Em andamento'), ('concluido', 'Concluído'), ('suspenso', 'Suspenso'), ('cancelado', 'Cancelado')], db_index=True, default='aberto', max_length=20),
        ),
        migrations.AlterField(
            model_name='chamado',
            name='suspenso_em',
            field=models.DateTimeField(blank=True, db_index=True, null=True),
        ),
        migrations.AlterField(
            model_name='chamadomensagem',
            name='anexo',
            field=models.FileField(blank=True, null=True, upload_to=solicitacoes.models.mensagem_upload_path),
        ),
        migrations.AlterField(
            model_name='chamadomensagem',
            name='criado_em',
            field=models.DateTimeField(db_index=True, default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='perguntatiposolicitacao',
            name='opcoes',
            field=models.CharField(blank=True, help_text="Para escolha/múltipla escolha, separe as opções por ';'.", max_length=800),
        ),
        migrations.AlterField(
            model_name='tiposolicitacao',
            name='setores_permitidos',
            field=models.CharField(blank=True, help_text="Nomes dos setores separados por ';' (ex.: RH; Financeiro; TI). Vazio = todos.", max_length=300),
        ),
        migrations.AddIndex(
            model_name='chamado',
            index=models.Index(fields=['status', 'criado_em'], name='solicitacoe_status_32c70e_idx'),
        ),
        migrations.AddIndex(
            model_name='chamadomensagem',
            index=models.Index(fields=['chamado', 'criado_em'], name='solicitacoe_chamado_fc39de_idx'),
        ),
        migrations.AddIndex(
            model_name='chamadomensagem',
            index=models.Index(fields=['visibilidade'], name='solicitacoe_visibil_32fd6e_idx'),
        ),
        migrations.AddConstraint(
            model_name='respostachamado',
            constraint=models.UniqueConstraint(fields=('chamado', 'pergunta'), name='uq_resposta_chamado_pergunta'),
        ),
        migrations.AddConstraint(
            model_name='secaovista',
            constraint=models.UniqueConstraint(fields=('user', 'secao'), name='uq_secao_vista_user_secao'),
        ),
        migrations.AddField(
            model_name='chamadovista',
            name='chamado',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vistas', to='solicitacoes.chamado'),
        ),
        migrations.AddField(
            model_name='chamadovista',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chamado_vistas', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddConstraint(
            model_name='chamadovista',
            constraint=models.UniqueConstraint(fields=('user', 'chamado'), name='uq_chamado_vista_user_chamado'),
        ),
    ]
