# Generated by Django 5.2.5 on 2025-09-10 12:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='gestao',
            field=models.CharField(choices=[('NA', 'Não é da Gestão'), ('ADM', 'Gestão Administrativa'), ('FIN', 'Gestão Financeira'), ('CFTV', 'Gestão CFTV'), ('TI', 'Gestão de TI')], default='NA', max_length=10, verbose_name='Área de Gestão'),
        ),
        migrations.AlterField(
            model_name='user',
            name='cargo',
            field=models.CharField(choices=[('ENGENHEIRO', 'ENGENHEIRO'), ('COORDENADOR', 'COORDENADOR'), ('TÉCNICO', 'TÉCNICO'), ('ESTAGIARIO', 'ESTAGIARIO'), ('ANALISTA', 'ANALISTA'), ('DIRETOR', 'DIRETOR'), ('ASSISTENTE ADM', 'ASSISTENTE ADM'), ('PROJETISTA', 'PROJETISTA')], default='ANALISTA', max_length=30, verbose_name='Cargo'),
        ),
        migrations.AlterField(
            model_name='user',
            name='perfil',
            field=models.CharField(choices=[('ADMINISTRATIVO', 'Administrador'), ('GESTOR', 'Gestor'), ('COLABORADOR', 'Colaborador'), ('SUPER TI', 'SUPER TI')], default='COLABORADOR', max_length=20, verbose_name='Perfil de acesso'),
        ),
        migrations.AlterField(
            model_name='user',
            name='setor',
            field=models.CharField(choices=[('FROTA', 'FROTA'), ('ADM/RH/DP', 'ADM/RH/DP'), ('SMS', 'SMS'), ('PLANEJAMENTO', 'PLANEJAMENTO'), ('RTCT', 'RTCT'), ('ELÉTRICA/AUTOMAÇÃO', 'ELÉTRICA/AUTOMAÇÃO'), ('PPCI/MECÂNICA', 'PPCI/MECÂNICA'), ('CIVIL/ARQUITETURA', 'CIVIL/ARQUITETURA'), ('PRODUÇÃO', 'PRODUÇÃO'), ('NOVOS NEGÓCIOS', 'NOVOS NEGÓCIOS'), ('DOC DE SEGURANÇA', 'DOC DE SEGURANÇA'), ('PROJETO CIVITAS', 'PROJETO CIVITAS')], default='ADM', max_length=30, verbose_name='Setor'),
        ),
    ]
