# Generated by Django 5.2.5 on 2025-09-10 14:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_user_gestao_alter_user_cargo_alter_user_perfil_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='gestao',
            field=models.CharField(choices=[('RICARDO', 'RICARDO MIRANDA'), ('FERNANDA', 'FERNANDA LAZZARI'), ('IVAN ', 'IVAN MORAIS'), ('ANDRÉ ', 'ANDRÉ HILLENSHEIM'), ('LUIZ  ', 'LUIZ EDUARDO OLIVEIRA')], default='NA', max_length=10, verbose_name='Área de Gestão'),
        ),
    ]
