# Generated by Django 5.2.5 on 2025-09-11 11:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_alter_user_gestao'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='gestao',
            field=models.CharField(choices=[('NA', 'Sem gestão'), ('RICARDO', 'RICARDO MIRANDA'), ('FERNANDA', 'FERNANDA LAZZARI'), ('IVAN', 'IVAN MORAIS'), ('ANDRE', 'ANDRÉ HILLENSHEIM'), ('LUIZ', 'LUIZ EDUARDO OLIVEIRA')], default='NA', max_length=30, verbose_name='Área de Gestão'),
        ),
        migrations.AlterField(
            model_name='user',
            name='perfil',
            field=models.CharField(choices=[('ADMINISTRADOR', 'Administrador'), ('GESTOR', 'Gestor'), ('COLABORADOR', 'Colaborador'), ('SUPER_TI', 'Super TI')], default='COLABORADOR', max_length=20, verbose_name='Perfil de acesso'),
        ),
        migrations.AlterField(
            model_name='user',
            name='setor',
            field=models.CharField(choices=[('FROTA', 'FROTA'), ('ADM/RH/DP', 'ADM/RH/DP'), ('SMS', 'SMS'), ('PLANEJAMENTO', 'PLANEJAMENTO'), ('RTCT', 'RTCT'), ('ELÉTRICA/AUTOMAÇÃO', 'ELÉTRICA/AUTOMAÇÃO'), ('PPCI/MECÂNICA', 'PPCI/MECÂNICA'), ('CIVIL/ARQUITETURA', 'CIVIL/ARQUITETURA'), ('PRODUÇÃO', 'PRODUÇÃO'), ('NOVOS NEGÓCIOS', 'NOVOS NEGÓCIOS'), ('DOC DE SEGURANÇA', 'DOC DE SEGURANÇA'), ('PROJETO CIVITAS', 'PROJETO CIVITAS')], default='ADM/RH/DP', max_length=30, verbose_name='Setor'),
        ),
    ]
