# Generated by Django 5.2.5 on 2025-09-04 19:45

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.CharField(max_length=64)),
                ('channel', models.CharField(choices=[('email', 'E-mail')], default='email', max_length=16)),
                ('to_email', models.EmailField(max_length=254)),
                ('subject', models.CharField(max_length=200)),
                ('body_text', models.TextField(blank=True)),
                ('body_html', models.TextField(blank=True)),
                ('is_sent', models.BooleanField(default=False)),
                ('error', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('sent_at', models.DateTimeField(blank=True, null=True)),
                ('ref_app', models.CharField(blank=True, max_length=50)),
                ('ref_model', models.CharField(blank=True, max_length=50)),
                ('ref_pk', models.CharField(blank=True, max_length=50)),
            ],
            options={
                'indexes': [models.Index(fields=['kind', 'created_at'], name='notificatio_kind_e256fc_idx')],
            },
        ),
        migrations.CreateModel(
            name='NotificationOptOut',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254)),
                ('kind', models.CharField(blank=True, max_length=64)),
            ],
            options={
                'unique_together': {('email', 'kind')},
            },
        ),
    ]
